[package]
name = "api"
version = "0.1.0"
description = "An example Tauri Application showcasing the api"
edition = "2021"
rust-version = "1.57"
license = "Apache-2.0 OR MIT"

[build-dependencies]
tauri-build = { path = "../../../core/tauri-build", features = ["isolation"] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
tauri = { path = "../../../core/tauri", features = ["api-all", "cli", "global-shortcut", "http-multipart", "icon-ico", "icon-png", "isolation", "macos-private-api", "reqwest-client", "system-tray", "updater"] }
tiny_http = "0.11"

[target."cfg(target_os = \"windows\")".dependencies]
window-vibrancy = "0.1"
window-shadows= "0.1"

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]

# default to small, optimized release binaries
[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"

[patch.crates-io]
tao = { git = "https://github.com/tauri-apps/tao.git", branch = "dev" }
libappindicator-sys = { git = "https://github.com/Beanow/libappindicator-rs.git", branch = "fix/linker" }
